networks:
  tycho:
    external: true

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "7777:7777"
    environment:
      - BUILD_TYPE=debug
      - REDIS_HOST=redis
      - REDIS_PORT=7777
      - REDIS_ARGS="--loglevel verbose"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - tycho

# --- --- --- Ops --- --- ---

  stream:
    build: 
      context: .
      dockerfile: back/ops/Dockerfile
      args:
        - PROGRAM=stream
        - BUILD_TYPE=debug
    ports:
      - "42042:42042"
    volumes:
     - ./back:/app
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - back/.env
    environment:
      - RUST_LOG="off,tycho_orderbook=trace,back=trace,stream=trace,shared=trace"
      - REDIS_HOST=redis
    restart: always
    networks:
      - tycho


# --- --- --- Frontend --- --- ---

  next:
    build:
      context: ./front/front
      dockerfile: ops/Dockerfile
      # Need to add RUN corepack enable && corepack prepare pnpm@latest --activate
    profiles:
      - ui  # Only launched when the "ui" profile is active: docker-compose --profile ui up
    ports:
      - "3000:3000"
    volumes:
      - ./front/front:/app
      - node_modules:/app/node_modules
    command: pnpm dev
    environment:
      - NEXT_PUBLIC_STREAM_API_URL=http://stream:42042
      - NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=572586a808fa0462edb485f181680943
      - API_HEADER_KEY=tycho-orderbook-web-api-key
      - API_HEADER_VALUE=42
      - APP_METADATA_SITE_URL=
    depends_on:
      - stream
    restart: always
    networks:
      - tycho

volumes:
  node_modules: