networks:
  tycho:
    external: true

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "7777:7777"
    environment:
      - BUILD_TYPE=debug
      - REDIS_HOST=redis
      - REDIS_PORT=7777
      - REDIS_ARGS="--loglevel verbose"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - tycho

  ethereum:
    build: 
      context: back
      dockerfile: ops/Dockerfile
      args:
        - PROGRAM=stream
    ports:
      - "42001:42001"
    volumes:
      - ./back:/app
      - ../tycho-orderbook-sdk:/tycho-orderbook-sdk
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - back/.env
    environment:
      - BUILD_TYPE=debug
      - REDIS_HOST=redis
      - NETWORK=ethereum
    restart: always
    networks:
      - tycho

# --- --- --- Ops --- --- ---

volumes:
  - ../:/workspace


# --- --- --- Frontend --- --- ---

  # web:
  #     build:
  #       context: front
  #       dockerfile: ops/Dockerfile
  #     ports:
  #       - "3000:3000"
  #     volumes:
  #       - ./front:/app
  #       - node_modules:/app/node_modules
  #     command: pnpm dev
  #     env_file: 
  #       - front/.env
  #     depends_on:
  #       - ethereum
  #     restart: always
  #     networks:
  #       - tycho
  
# volumes:
#   node_modules: