{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tycho-orderbook-stream.fullname" . }}-ext-secret
  labels:
    {{- include "tycho-orderbook-stream.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.externalSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretstore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "tycho-orderbook-stream.fullname" . }}-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.data }}
{{- end }}
